# Generated by Django 5.0.6 on 2024-07-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='numroom',
            field=models.IntegerField(default=1),
        ),
    ]
