# Generated by Django 5.0.6 on 2024-07-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='projectname',
            new_name='project',
        ),
    ]
