# Generated by Django 4.2.2 on 2024-07-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0004_rename_projectname_room_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#4154f1', max_length=7),
        ),
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='window_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='window_orientation',
            field=models.CharField(default='', max_length=5),
        ),
    ]
