# Generated by Django 4.2.2 on 2024-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0005_room_color_room_occupants_room_window_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='illumination_req',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='room',
            name='window_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='window_orientation',
            field=models.CharField(default='', max_length=11),
        ),
    ]
