# Generated by Django 4.2.2 on 2024-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0006_room_illumination_req_room_window_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='illumination_req',
            field=models.IntegerField(),
        ),
    ]
