# Generated by Django 4.2.2 on 2024-07-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0007_alter_room_illumination_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='illumination_req',
        ),
    ]
