# Generated by Django 4.2.2 on 2024-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0008_remove_room_illumination_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='illumination_req',
            field=models.IntegerField(default=200),
        ),
    ]
