# Generated by Django 5.0.7 on 2024-07-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEMWebApp', '0009_room_illumination_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='aircond_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='lamp_specs',
            field=models.CharField(default='', max_length=50),
        ),
    ]
